#include "ws2812.h"

// LED buffer
#ifndef WS2812_COUNT
#define WS2812_COUNT 1
#endif

__xdata uint8_t led_buffer[WS2812_COUNT * 3];

void ws2812_set_color(uint8_t index, uint8_t r, uint8_t g, uint8_t b) {
    if (index >= WS2812_COUNT) return;
    led_buffer[index * 3 + 0] = g; // WS2812 expects GRB
    led_buffer[index * 3 + 1] = r;
    led_buffer[index * 3 + 2] = b;
}

// SDCC specific: inline assembly for precise timing
// CH552 @ 24MHz: 1 cycle = ~41.6ns
// T0H: 400ns (+/- 150ns) -> ~10 cycles
// T0L: 850ns (+/- 150ns) -> ~20 cycles
// T1H: 800ns (+/- 150ns) -> ~19 cycles
// T1L: 450ns (+/- 150ns) -> ~11 cycles

// Since we can't easily template the PIN bit in pure ASM without complex macros,
// we'll use a slightly less efficient C/ASM mix or assume a specific pin map.
// HOWEVER, FAK uses a dynamic pin generation. 
// To keep it simple and generic for this implementation, we will use a C macro wrapper 
// generated by Nickel to define the port/pin set logic, or just simple bit-banging if the compiler optimizes well.

// For reliability on 8051 with strict timing, we often need full ASM.
// Here is a simplified version. For production reliability, this often needs tuning per pin.

void ws2812_show(void) {
    // Disable interrupts for timing
    EA = 0;
    
    uint8_t i;
    uint8_t j;
    uint8_t byte;

    for (i = 0; i < WS2812_COUNT * 3; i++) {
        byte = led_buffer[i];
        for (j = 0; j < 8; j++) {
            if (byte & 0x80) {
                // Send '1'
                WS2812_PIN = 1;
                // T1H: ~800ns (~19 cycles) -> 1 set + 18 nops
                // Reduced to 14 nops to be safe against overhead/2-cycle instructions
                __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop");
                __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop");
                __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop");
                __asm__("nop"); __asm__("nop");
                
                WS2812_PIN = 0;
                // T1L: ~450ns (~11 cycles) -> 1 clear + ~10 nops (minus loop overhead)
                // Loop overhead is likely 4-5 cycles. Let's add 6 nops.
                __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop");
                __asm__("nop"); __asm__("nop");
            } else {
                // Send '0'
                WS2812_PIN = 1;
                // T0H: ~400ns (~10 cycles) -> 1 set + 9 nops
                // Reduced to 6 nops
                __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop");
                __asm__("nop"); __asm__("nop");

                WS2812_PIN = 0;
                // T0L: ~850ns (~20 cycles) -> 1 clear + ~19 nops (minus loop overhead)
                // Loop overhead is likely 4-5 cycles. Let's add 15 nops.
                __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop");
                __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop");
                __asm__("nop"); __asm__("nop"); __asm__("nop"); __asm__("nop");
                __asm__("nop"); __asm__("nop"); __asm__("nop");
            }
            byte <<= 1;
        }
    }

    EA = 1;
    // Reset time (>50us)
}
